#!/bin/bash 

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CONFIG_PATH=~/.instapaper2koborc

echo "# reading config file ${CONFIG_PATH}"
source ${CONFIG_PATH}

echo "# downloading epub to dropbox"
perl ${CURRENT_DIR}/lwp.pl ${INSTAPAPER_USERNAME} ${INSTAPAPER_PASSWORD} || exit

echo
echo "# All done, now wait for dropbox sync"
echo
