#!/bin/bash 

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CONFIG_PATH=~/.instapaper2koborc

echo "# reading config file ${CONFIG_PATH}"
source ${CONFIG_PATH}

echo "# converting feed to dropbox using calibre"
ebook-convert Instapaper.recipe ${DROPBOX_PATH}/Public/instapaper.epub --username ${INSTAPAPER_USERNAME} --password ${INSTAPAPER_PASSWORD}

echo
echo "# All done, now wait for dropbox sync"
echo
